Both 7 and 8

diff --git a/home/bin/ssebou/bin/komparecerts b/home/bin/ssebou/bin/komparecerts
--- a/home/bin/ssebou/bin/komparecerts
+++ b/home/bin/ssebou/bin/komparecerts
@@ -1,13 +1,23 @@
 #!/bin/bash
 
-echo ================= FROM KEYSTORAGE
-JAVA_HOME=/opt/mbapps/java/jdk1.8.0_162
-JAVA_HOME=/opt/mbapps/java/jdk1.7.0_80
-JAVA_HOME=/home/shared/jdk1.8.0_162
-JAVA_HOME=/home/shared/jdk1.7.0_80
+
+JDKROOTDIR=/opt/mbapps/java
+JDKROOTDIR=/home/shared
+
+JAVA8_HOME=${JDKROOTDIR}/jdk1.8.0_162
+JAVA7_HOME=${JDKROOTDIR}/jdk1.7.0_80
+
 ALIAS=$(hostname).maxbill.com
+
 KSTMPF=/tmp/ks.cert
-cd $JAVA_HOME && ./bin/keytool -exportcert -keystore ./jre/lib/security/cacerts -alias $ALIAS -file $KSTMPF -storepass changeit 
-openssl x509 -inform der -in $KSTMPF 
-echo ================= FROM SERVER
-openssl s_client -connect ${ALIAS}:443 </dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' 
+JKSPAS=changeit
+for j in $JAVA7_HOME $JAVA8_HOME; do 
+	[[ -x "$j" ]] || { echo "JAVA_HOME not found there: $j" ; continue ; }
+	JKS=$j/jre/lib/security/cacerts
+	JKT=$j/bin/keytool
+	echo ================= FROM $JKS KEYSTORAGE
+	$JKT -exportcert -keystore $JKS -alias $ALIAS -file $KSTMPF -storepass $JKSPAS
+	openssl x509 -inform der -in $KSTMPF 
+	echo ================= FROM $ALIAS SERVER
+	openssl s_client -connect ${ALIAS}:443 </dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' 
+done 
